export const mainMenuData = [
  {
    wbUserRightId: 79132,
    wbUserId: 2,
    wbMenuId: 297,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Order Setup",
    userMenuUrl: null,
    slNo: 1,
    childMenu: [
      {
        wbUserRightId: 79372,
        wbUserId: 2,
        wbMenuId: 446,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "DPU Setup",
        userMenuUrl: null,
        slNo: 1,
        childMenu: [
          {
            wbUserRightId: 79373,
            wbUserId: 2,
            wbMenuId: 447,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order Approval Status",
            userMenuUrl: "~/Setup/Orders/OrderApprovalStatus.aspx",
            slNo: 1,
            childMenu: [],
          },
          {
            wbUserRightId: 79377,
            wbUserId: 2,
            wbMenuId: 448,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order CP Status",
            userMenuUrl: "~/Setup/Orders/OrderCPStatus.aspx",
            slNo: 2,
            childMenu: [],
          },
          {
            wbUserRightId: 79378,
            wbUserId: 2,
            wbMenuId: 449,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order S&I Status",
            userMenuUrl: "~/Setup/Orders/OrderSIVStatus.aspx",
            slNo: 3,
            childMenu: [],
          },
          {
            wbUserRightId: 79381,
            wbUserId: 2,
            wbMenuId: 450,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order Pro Sample Test Status",
            userMenuUrl: "~/Setup/Orders/OrderPSTRStatus.aspx",
            slNo: 4,
            childMenu: [],
          },
          {
            wbUserRightId: 79382,
            wbUserId: 2,
            wbMenuId: 451,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order Lab Status",
            userMenuUrl: "~/Setup/Orders/OrderLabStatus.aspx",
            slNo: 5,
            childMenu: [],
          },
          {
            wbUserRightId: 79384,
            wbUserId: 2,
            wbMenuId: 452,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order Critical Path Status",
            userMenuUrl: "~/Setup/Orders/OrderCriticalStatus.aspx",
            slNo: 6,
            childMenu: [],
          },
          {
            wbUserRightId: 79385,
            wbUserId: 2,
            wbMenuId: 453,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order Material Status",
            userMenuUrl: "~/Setup/Orders/OrderMaterialStatus.aspx",
            slNo: 7,
            childMenu: [],
          },
          {
            wbUserRightId: 79386,
            wbUserId: 2,
            wbMenuId: 454,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Shipping Status",
            userMenuUrl: "~/Setup/Orders/OrderShippingStatus.aspx",
            slNo: 8,
            childMenu: [],
          },
          {
            wbUserRightId: 79387,
            wbUserId: 2,
            wbMenuId: 455,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Production Sample Status",
            userMenuUrl: "~/Setup/Orders/OrderPSStatus.aspx",
            slNo: 9,
            childMenu: [],
          },
          {
            wbUserRightId: 79388,
            wbUserId: 2,
            wbMenuId: 456,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Production Status",
            userMenuUrl: "~/Setup/Orders/OrderProductionStatus.aspx",
            slNo: 10,
            childMenu: [],
          },
          {
            wbUserRightId: 79389,
            wbUserId: 2,
            wbMenuId: 457,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 446,
            wbCanPermission: null,
            userMenuName: "Order OKTS",
            userMenuUrl: "~/Setup/Orders/OrderOKTS.aspx",
            slNo: 11,
            childMenu: [],
          },
        ],
      },
      {
        wbUserRightId: 79306,
        wbUserId: 2,
        wbMenuId: 381,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Production Sample Type",
        userMenuUrl: "~/Setup/Orders/ProductionSampleType.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 79297,
        wbUserId: 2,
        wbMenuId: 364,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Box Type Retailer",
        userMenuUrl: "~/Setup/Orders/BoxTypeRetailer.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 79166,
        wbUserId: 2,
        wbMenuId: 299,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Colour",
        userMenuUrl: "~/Setup/Colour.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 79298,
        wbUserId: 2,
        wbMenuId: 370,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Destination Retailer",
        userMenuUrl: "~/Setup/Orders/DestinationRetailer.aspx",
        slNo: 3,
        childMenu: [],
      },
      {
        wbUserRightId: 79299,
        wbUserId: 2,
        wbMenuId: 369,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Factory Retailer",
        userMenuUrl: "~/Setup/Orders/FactoryRetailer.aspx",
        slNo: 4,
        childMenu: [],
      },
      {
        wbUserRightId: 79228,
        wbUserId: 2,
        wbMenuId: 302,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Lab Dip Reference",
        userMenuUrl: "~/Setup/OrderLabDipRef.aspx",
        slNo: 5,
        childMenu: [],
      },
      {
        wbUserRightId: 79235,
        wbUserId: 2,
        wbMenuId: 303,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Trim Categories",
        userMenuUrl: "~/Setup/BasicTrimType.aspx",
        slNo: 6,
        childMenu: [],
      },
      {
        wbUserRightId: 79252,
        wbUserId: 2,
        wbMenuId: 304,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Add New Trim",
        userMenuUrl: "~/Setup/Orders/OrderBasicTrim.aspx",
        slNo: 7,
        childMenu: [],
      },
      {
        wbUserRightId: 79255,
        wbUserId: 2,
        wbMenuId: 305,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Basic Trim Set",
        userMenuUrl: "~/Setup/Orders/OrderBasicTrimLog.aspx",
        slNo: 8,
        childMenu: [],
      },
      {
        wbUserRightId: 79300,
        wbUserId: 2,
        wbMenuId: 368,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "PO Mode Retailer",
        userMenuUrl: "~/Setup/Orders/ShipModeRetailer.aspx",
        slNo: 9,
        childMenu: [],
      },
      {
        wbUserRightId: 79301,
        wbUserId: 2,
        wbMenuId: 367,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "PO Type Retailer",
        userMenuUrl: "~/Setup/Orders/PoTypeRetailer.aspx",
        slNo: 10,
        childMenu: [],
      },
      {
        wbUserRightId: 79307,
        wbUserId: 2,
        wbMenuId: 374,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Notes Retailer",
        userMenuUrl: "~/Setup/Orders/OrderNoteRetailer.aspx",
        slNo: 11,
        childMenu: [],
      },
      {
        wbUserRightId: 79308,
        wbUserId: 2,
        wbMenuId: 373,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Season Retailer",
        userMenuUrl: "~/Setup/Orders/OrderSeasonRetailer.aspx",
        slNo: 12,
        childMenu: [],
      },
      {
        wbUserRightId: 79287,
        wbUserId: 2,
        wbMenuId: 310,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Size Details",
        userMenuUrl: "~/Setup/SizeDetails.aspx",
        slNo: 13,
        childMenu: [],
      },
      {
        wbUserRightId: 79304,
        wbUserId: 2,
        wbMenuId: 371,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Pack Type Retailer",
        userMenuUrl: "~/Setup/Orders/OrderPackTypeRetailer.aspx",
        slNo: 13,
        childMenu: [],
      },
      {
        wbUserRightId: 79310,
        wbUserId: 2,
        wbMenuId: 383,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Mail Body",
        userMenuUrl: "~/Setup/Orders/OrderMailBody.aspx",
        slNo: 14,
        childMenu: [],
      },
      {
        wbUserRightId: 79311,
        wbUserId: 2,
        wbMenuId: 384,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Mail To Group",
        userMenuUrl: "~/Setup/Orders/OrderMailToGroup.aspx",
        slNo: 15,
        childMenu: [],
      },
      {
        wbUserRightId: 79314,
        wbUserId: 2,
        wbMenuId: 387,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Currency Symbol",
        userMenuUrl: "~/Setup/Orders/OrderCurrencySymbol.aspx",
        slNo: 16,
        childMenu: [],
      },
      {
        wbUserRightId: 79317,
        wbUserId: 2,
        wbMenuId: 390,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Status",
        userMenuUrl: "~/Setup/Orders/OrderStatus.aspx",
        slNo: 17,
        childMenu: [],
      },
      {
        wbUserRightId: 79318,
        wbUserId: 2,
        wbMenuId: 391,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Reason",
        userMenuUrl: "~/Setup/Orders/OrderReason.aspx",
        slNo: 18,
        childMenu: [],
      },
      {
        wbUserRightId: 79319,
        wbUserId: 2,
        wbMenuId: 392,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Responsible",
        userMenuUrl: "~/Setup/Orders/OrderResponsible.aspx",
        slNo: 19,
        childMenu: [],
      },
      {
        wbUserRightId: 79320,
        wbUserId: 2,
        wbMenuId: 393,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Order Factory Setup",
        userMenuUrl: "~/Setup/Orders/OrderFactorySetupMst.aspx",
        slNo: 20,
        childMenu: [],
      },
      {
        wbUserRightId: 79330,
        wbUserId: 2,
        wbMenuId: 402,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "OK STATUS",
        userMenuUrl: "~/Setup/Orders/OrderOKTS.aspx",
        slNo: 26,
        childMenu: [],
      },
      {
        wbUserRightId: 79331,
        wbUserId: 2,
        wbMenuId: 403,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "MANUFACTURING",
        userMenuUrl: "~/Setup/Orders/OrderManufacturing.aspx",
        slNo: 27,
        childMenu: [],
      },
      {
        wbUserRightId: 79332,
        wbUserId: 2,
        wbMenuId: 404,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "LINE & FLOOR",
        userMenuUrl: "~/Setup/Orders/OrderLine.aspx",
        slNo: 28,
        childMenu: [],
      },
      {
        wbUserRightId: 148196,
        wbUserId: 2,
        wbMenuId: 70497,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Printer Setup",
        userMenuUrl: "~/Setup/Orders/PrinterName.aspx",
        slNo: 29,
        childMenu: [],
      },
      {
        wbUserRightId: 148197,
        wbUserId: 2,
        wbMenuId: 70498,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Label Supplier Setup",
        userMenuUrl: "~/Setup/Orders/LabelSupplier.aspx",
        slNo: 30,
        childMenu: [],
      },
      {
        wbUserRightId: 148198,
        wbUserId: 2,
        wbMenuId: 70499,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 297,
        wbCanPermission: null,
        userMenuName: "Transport Setup",
        userMenuUrl: "~/Setup/Orders/Transport.aspx",
        slNo: 31,
        childMenu: [],
      },
    ],
  },
  {
    wbUserRightId: 79052,
    wbUserId: 2,
    wbMenuId: 116,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "New Order",
    userMenuUrl: "~/Orders/NewOrder.aspx",
    slNo: 2,
    childMenu: [],
  },
  {
    wbUserRightId: 79053,
    wbUserId: 2,
    wbMenuId: 117,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Order Editor",
    userMenuUrl: null,
    slNo: 3,
    childMenu: [
      {
        wbUserRightId: 79136,
        wbUserId: 2,
        wbMenuId: 311,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 117,
        wbCanPermission: null,
        userMenuName: "Order Print Single",
        userMenuUrl: null,
        slNo: 1,
        childMenu: [
          {
            wbUserRightId: 79137,
            wbUserId: 2,
            wbMenuId: 312,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 311,
            wbCanPermission: null,
            userMenuName: "Incomplete Order Print Single",
            userMenuUrl: "~/Orders/EditOrderPrint.aspx",
            slNo: 1,
            childMenu: [],
          },
          {
            wbUserRightId: 79164,
            wbUserId: 2,
            wbMenuId: 313,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 311,
            wbCanPermission: null,
            userMenuName: "Amend Order Print Single",
            userMenuUrl: "~/Orders/AmendOrderPrint.aspx",
            slNo: 2,
            childMenu: [],
          },
          {
            wbUserRightId: 79195,
            wbUserId: 2,
            wbMenuId: 314,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 311,
            wbCanPermission: null,
            userMenuName: "Order Print Single Report",
            userMenuUrl: "~/Report/OrderReportForm/SinglePrintOrderForm.aspx",
            slNo: 3,
            childMenu: [],
          },
          {
            wbUserRightId: 79417,
            wbUserId: 2,
            wbMenuId: 491,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 311,
            wbCanPermission: null,
            userMenuName: "NP Print Single Report",
            userMenuUrl:
              "~/Report/OrderReportForm/SinglePrintNinetyOrderForm.aspx",
            slNo: 4,
            childMenu: [],
          },
        ],
      },
      {
        wbUserRightId: 79139,
        wbUserId: 2,
        wbMenuId: 315,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 117,
        wbCanPermission: null,
        userMenuName: "Order Multi Product",
        userMenuUrl: null,
        slNo: 2,
        childMenu: [
          {
            wbUserRightId: 79138,
            wbUserId: 2,
            wbMenuId: 316,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 315,
            wbCanPermission: null,
            userMenuName: "Incomplete Order Multi Product",
            userMenuUrl: "~/Orders/EditOrderPrintMulti.aspx",
            slNo: 1,
            childMenu: [],
          },
          {
            wbUserRightId: 79163,
            wbUserId: 2,
            wbMenuId: 317,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 315,
            wbCanPermission: null,
            userMenuName: "Amend Order Multi Product",
            userMenuUrl: "~/Orders/AmendOrderPrintMulti.aspx",
            slNo: 2,
            childMenu: [],
          },
          {
            wbUserRightId: 79196,
            wbUserId: 2,
            wbMenuId: 318,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 315,
            wbCanPermission: null,
            userMenuName: "Order Multi Product Report",
            userMenuUrl: "~/Report/OrderReportForm/MultiPrintOrderForm.aspx",
            slNo: 3,
            childMenu: [],
          },
        ],
      },
      {
        wbUserRightId: 79142,
        wbUserId: 2,
        wbMenuId: 319,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 117,
        wbCanPermission: null,
        userMenuName: "Order Non Print Single",
        userMenuUrl: null,
        slNo: 3,
        childMenu: [
          {
            wbUserRightId: 79141,
            wbUserId: 2,
            wbMenuId: 320,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 319,
            wbCanPermission: null,
            userMenuName: "Incomplete Order Non Print Single",
            userMenuUrl: "~/Orders/EditOrderNonPrint.aspx",
            slNo: 1,
            childMenu: [],
          },
          {
            wbUserRightId: 79161,
            wbUserId: 2,
            wbMenuId: 321,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 319,
            wbCanPermission: null,
            userMenuName: "Amend Order Non Print Single",
            userMenuUrl: "~/Orders/AmendOrderNonPrint.aspx",
            slNo: 2,
            childMenu: [],
          },
          {
            wbUserRightId: 79198,
            wbUserId: 2,
            wbMenuId: 323,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 319,
            wbCanPermission: null,
            userMenuName: "Order Non Print Single Report",
            userMenuUrl:
              "~/Report/OrderReportForm/SingleNonPrintOrderForm.aspx",
            slNo: 3,
            childMenu: [],
          },
          {
            wbUserRightId: 79418,
            wbUserId: 2,
            wbMenuId: 492,
            wbCanEdit: false,
            wbCanDelete: false,
            wbCanView: true,
            wbParentId: 319,
            wbCanPermission: null,
            userMenuName: "NP Shape Single Report",
            userMenuUrl:
              "~/Report/OrderReportForm/SingleNonPrintNinetyOrderForm.aspx",
            slNo: 4,
            childMenu: [],
          },
        ],
      },
    ],
  },
  {
    wbUserRightId: 79416,
    wbUserId: 2,
    wbMenuId: 490,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Order GridView PO Wise",
    userMenuUrl: "~/Orders/OrderGridViewPoWise.aspx",
    slNo: 4,
    childMenu: [],
  },
  {
    wbUserRightId: 79316,
    wbUserId: 2,
    wbMenuId: 389,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Amend Order TBC Sample",
    userMenuUrl: "~/Orders/AmendOrderTbc.aspx",
    slNo: 5,
    childMenu: [],
  },
  {
    wbUserRightId: 79323,
    wbUserId: 2,
    wbMenuId: 396,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Daily Production Update",
    userMenuUrl: "~/Orders/OrderDailyProdGridViewPoWise.aspx",
    slNo: 6,
    childMenu: [],
  },
  {
    wbUserRightId: 79324,
    wbUserId: 2,
    wbMenuId: 405,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Daily Production Update Factory",
    userMenuUrl: "~/Orders/OrderDailyProductionUpdatePoWise.aspx",
    slNo: 7,
    childMenu: [],
  },
  {
    wbUserRightId: 79349,
    wbUserId: 2,
    wbMenuId: 422,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Trim Library",
    userMenuUrl: null,
    slNo: 8,
    childMenu: [
      {
        wbUserRightId: 79348,
        wbUserId: 2,
        wbMenuId: 423,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Add New Trims",
        userMenuUrl: "~/TrimLibrary/TrimLibraryMain.aspx",
        slNo: 1,
        childMenu: [],
      },
      {
        wbUserRightId: 79350,
        wbUserId: 2,
        wbMenuId: 424,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Trim Library View",
        userMenuUrl: "~/TrimLibrary/TrimLibraryCardView.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 158196,
        wbUserId: 2,
        wbMenuId: 80497,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "New Trim Card",
        userMenuUrl: "~/TrimLibrary/TrimCardStart.aspx",
        slNo: 3,
        childMenu: [],
      },
      {
        wbUserRightId: 158198,
        wbUserId: 2,
        wbMenuId: 80499,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Incomplete Trim Card",
        userMenuUrl: "~/TrimLibrary/TrimCardEdit.aspx",
        slNo: 4,
        childMenu: [],
      },
      {
        wbUserRightId: 158199,
        wbUserId: 2,
        wbMenuId: 80500,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Amend Trim Card",
        userMenuUrl: "~/TrimLibrary/TrimCardAmend.aspx",
        slNo: 5,
        childMenu: [],
      },
      {
        wbUserRightId: 158200,
        wbUserId: 2,
        wbMenuId: 80501,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Trim Gridview",
        userMenuUrl: "~/TrimLibrary/TrimCardGrid.aspx",
        slNo: 6,
        childMenu: [],
      },
      {
        wbUserRightId: 158197,
        wbUserId: 2,
        wbMenuId: 80498,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Trim Card Report",
        userMenuUrl: "~/Report/TrimReportForm/RptTrimCardForm.aspx",
        slNo: 7,
        childMenu: [],
      },
      {
        wbUserRightId: 158201,
        wbUserId: 2,
        wbMenuId: 80502,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 422,
        wbCanPermission: null,
        userMenuName: "Trim Supplier Setup",
        userMenuUrl: "~/Setup/TrimLibrary/TrimSupplier.aspx",
        slNo: 8,
        childMenu: [],
      },
    ],
  },
  {
    wbUserRightId: 79370,
    wbUserId: 2,
    wbMenuId: 444,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Fabric Consumption ",
    userMenuUrl: "~/Orders/PoConsumtionEntry.aspx",
    slNo: 9,
    childMenu: [],
  },
  {
    wbUserRightId: 79371,
    wbUserId: 2,
    wbMenuId: 445,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "DPU Shipping & Invoice",
    userMenuUrl: "~/Orders/OrderDailyUpdateShippingInvoice.aspx",
    slNo: 9,
    childMenu: [],
  },
  {
    wbUserRightId: 79391,
    wbUserId: 2,
    wbMenuId: 464,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "DPU",
    userMenuUrl: null,
    slNo: 10,
    childMenu: [
      {
        wbUserRightId: 79390,
        wbUserId: 2,
        wbMenuId: 465,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 464,
        wbCanPermission: null,
        userMenuName: "Daily Production Update",
        userMenuUrl: "~/Orders/OrderDailyProdGridViewPoWise.aspx",
        slNo: 1,
        childMenu: [],
      },
      {
        wbUserRightId: 79392,
        wbUserId: 2,
        wbMenuId: 466,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 464,
        wbCanPermission: null,
        userMenuName: "Daily Production Update Factory",
        userMenuUrl: "~/Orders/OrderDailyProductionUpdatePoWise.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 79393,
        wbUserId: 2,
        wbMenuId: 467,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 464,
        wbCanPermission: null,
        userMenuName: "Daily Production General View",
        userMenuUrl: "~/Orders/OrderDailyUpdateGV.aspx",
        slNo: 3,
        childMenu: [],
      },
      {
        wbUserRightId: 79394,
        wbUserId: 2,
        wbMenuId: 468,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 464,
        wbCanPermission: null,
        userMenuName: "Daily Production Material Delivery",
        userMenuUrl: "~/Orders/OrderDailyUpdateMDL.aspx",
        slNo: 4,
        childMenu: [],
      },
      {
        wbUserRightId: 79395,
        wbUserId: 2,
        wbMenuId: 469,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 464,
        wbCanPermission: null,
        userMenuName: "Daily Production CP",
        userMenuUrl: "~/Orders/OrderDailyUpdateACP.aspx",
        slNo: 5,
        childMenu: [],
      },
      {
        wbUserRightId: 79396,
        wbUserId: 2,
        wbMenuId: 470,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 464,
        wbCanPermission: null,
        userMenuName: "DPU Shipping & Invoice",
        userMenuUrl: "~/Orders/OrderDailyUpdateShippingInvoice.aspx",
        slNo: 6,
        childMenu: [],
      },
    ],
  },
  {
    wbUserRightId: 79375,
    wbUserId: 2,
    wbMenuId: 458,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "PM DPU",
    userMenuUrl: null,
    slNo: 11,
    childMenu: [
      {
        wbUserRightId: 79374,
        wbUserId: 2,
        wbMenuId: 459,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 458,
        wbCanPermission: null,
        userMenuName: "PM & PENNEYS Daily Production Update",
        userMenuUrl: "~/Orders/OrderDailyProdPrimarkAll.aspx",
        slNo: 1,
        childMenu: [],
      },
      {
        wbUserRightId: 79376,
        wbUserId: 2,
        wbMenuId: 460,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 458,
        wbCanPermission: null,
        userMenuName: "PM & PENNEYS General View",
        userMenuUrl: "~/Orders/OrderDailyPrimarkGeneralView.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 79379,
        wbUserId: 2,
        wbMenuId: 461,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 458,
        wbCanPermission: null,
        userMenuName: "PM & PENNEYS CP",
        userMenuUrl: "~/Orders/OrderDailyPrimarkACP.aspx",
        slNo: 3,
        childMenu: [],
      },
      {
        wbUserRightId: 79380,
        wbUserId: 2,
        wbMenuId: 462,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 458,
        wbCanPermission: null,
        userMenuName: "PM & PENNEYS Material Delivery",
        userMenuUrl: "~/Orders/OrderDailyPrimarkMDL.aspx",
        slNo: 4,
        childMenu: [],
      },
      {
        wbUserRightId: 79383,
        wbUserId: 2,
        wbMenuId: 463,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 458,
        wbCanPermission: null,
        userMenuName: "PM & PENNEYS Shipping & Invoice",
        userMenuUrl: "~/Orders/OrderDailyPrimarkSI.aspx",
        slNo: 5,
        childMenu: [],
      },
    ],
  },
  {
    wbUserRightId: 79403,
    wbUserId: 2,
    wbMenuId: 477,
    wbCanEdit: false,
    wbCanDelete: false,
    wbCanView: true,
    wbParentId: 89,
    wbCanPermission: null,
    userMenuName: "Turkey DPU",
    userMenuUrl: null,
    slNo: 12,
    childMenu: [
      {
        wbUserRightId: 79405,
        wbUserId: 2,
        wbMenuId: 479,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 477,
        wbCanPermission: null,
        userMenuName: "TR Daily Production Update",
        userMenuUrl: "~/Orders/OrderDailyPoWiseTurkey.aspx",
        slNo: 1,
        childMenu: [],
      },
      {
        wbUserRightId: 79406,
        wbUserId: 2,
        wbMenuId: 480,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 477,
        wbCanPermission: null,
        userMenuName: "TR CP",
        userMenuUrl: "~/Orders/OrderDailyPoWiseTurkeyCP.aspx",
        slNo: 2,
        childMenu: [],
      },
      {
        wbUserRightId: 79407,
        wbUserId: 2,
        wbMenuId: 481,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 477,
        wbCanPermission: null,
        userMenuName: "TR Line Monitor",
        userMenuUrl: "~/Orders/OrderDailyPoWiseTurkeyLM.aspx",
        slNo: 3,
        childMenu: [],
      },
      {
        wbUserRightId: 118194,
        wbUserId: 2,
        wbMenuId: 40495,
        wbCanEdit: false,
        wbCanDelete: false,
        wbCanView: true,
        wbParentId: 477,
        wbCanPermission: null,
        userMenuName: "TR FINANCE AND INVOICING",
        userMenuUrl: "~/Orders/OrderTurkeyFinancialAnalysis.aspx",
        slNo: 4,
        childMenu: [],
      },
    ],
  },
];
